### ISSUE TITLE
The initial schema state.

### ISSUE THREAD

**Issue by rocketNeck** [learn-co-curriculum/nyc-sinatra#29]
In the readme for this lab it states that we should create migrations to match the tables that are displayed. Also in /db/migrate/01_create_landmarks.rb  there are instructions to "Write CreateLandmarks migration here"

however

In /db/schema.rb we can see that the landmarks table has already been created prior to the start of the student beginning the lab. Also of note is that the table in schema.rb is not the same as the table represented in the readme .  It has datetime columns.

**Comment by AnnJohn** [comment]
for web 0416
