### ISSUE TITLE
controllers sometimes load out of order

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-curriculum/nyc-sinatra#33]
add `sort` to config/environment `Dir[File.join(File.dirname(__FILE__), "../app/controllers", "*.rb")].each {|f| require f}`, because file order isn't guaranteed and sometimes the application controller is required after the other controller (causing an `uninitialized constant` error).

fix: Dir[File.join(File.dirname(**FILE**), "../app/controllers", "*.rb")].sort.each {|f| require f}

**Comment by joshuabamboo** [comment]
@PeterBell

**Comment by mendelB** [comment]
Logan mentioned that this is an issue with the IDE/linux machines due to lack of assured order of file loading

**Comment by mendelB** [comment]
@pletcher A couple of students have experienced this issue, does the fix submitted fix make sense at all?

**Comment by PeterBell** [comment]
Seems plausible to me - merging in. If you _don't_ like this @pletcher just let me know and I'll revert!

**Comment by pletcher** [comment]
Oh shoot -- @mendelB and I talked offline about a _slight_ improvement (explicitly requiring `application_controller.rb` before other controllers). This assumes a pretty flat controller hierarchy (which I think we can do), but it gets around assuming that controllers will necessarily be in alphabetical order (or that alphabetical order is the right order -- the `sort` solution will, of course, break if someone introduces a controller whose name comes before `application`).

But I think we can apply it on top of #34 :)

**Comment by PeterBell** [comment]
Hey @pletcher makes sense - mind just submitting and merging in a new PR?

**Comment by mendelB** [comment]
Hey yes sorry I wasn't able to get to making that fix yet, will be done
this afternoon!

On Tue, Jun 21, 2016 at 12:41 PM, Peter Bell notifications@github.com
wrote:

> Hey @pletcher https://github.com/pletcher makes sense - mind just
> submitting and merging in a new PR?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/learn-co-curriculum/nyc-sinatra/issues/33#issuecomment-227498666,
> or mute the thread
> https://github.com/notifications/unsubscribe/AL16eaaIJHDlgiIU8mTCdZET8DJUthtOks5qOBQ7gaJpZM4IvUQk
> .

## 

Mendel Blesofsky
