### ISSUE TITLE
tests use views

### ISSUE THREAD

**Issue by bhollan** [learn-co-curriculum/nyc-sinatra#37]
The controller tests for this lab should be re-factored to use the view mechanics a bit less.

CC: @aturkewi

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#43.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
