### ISSUE TITLE
Moving "Join Tables" explanation

### ISSUE THREAD

**Issue by kyleblee** [learn-co-curriculum/nyc-sinatra#40]
It might be helpful to move this explanation of join tables to the previous lab "Sinatra Playlister". The concept is used in both labs, but causes confusion in the previous lab when students are setting up their associations / db (questions were popping up in the "Ask a Question" feature). Then, it is described in detail here (in "Sinatra NYC"), after the student has already struggled through it and no longer needs the help. 

Just a thought.

**Comment by kyleblee** [comment]
The same could be same about the corresponding "Models" section, here.

**Comment by curiositypaths** [comment]
Hi there,

Thank you for the suggestion. We will update the `Sinatra Playlister` readme.

As always thank you for contributing.
