### ISSUE TITLE
Add "Don't forget to run rake db:seed" to instructions.

### ISSUE THREAD

**Issue by alexcrisan** [learn-co-curriculum/nyc-sinatra#48]
An instructor and I spent almost an hour trying to figure out why my controller's route's instance variable wasn't showing anything in the view. It would have been nice if the instructions mentioned running rake db:migrate so that the list would be populated, otherwise nothing shows up in the view pages.

**Comment by curiositypaths** [comment]
Hi there, 

Thank you for bringing this to our attention. We added a reference to the seed data in the README.

As always thank you for contributing!
