### ISSUE TITLE
Figures controller solution uses `post` method instead of `patch` for update action

### ISSUE THREAD

**Issue by joshuabamboo** [learn-co-curriculum/nyc-sinatra#49]
This should be a `patch` not `post` -- https://github.com/learn-co-curriculum/nyc-sinatra/blob/solution/app/controllers/figures_controller.rb#L37

[The form is making a patch request](https://github.com/learn-co-curriculum/nyc-sinatra/blob/solution/app/views/figures/edit.erb#L2)

Note: In order for it to interpret the `patch` in the controller, `use Rack::MethodOverride` needs to be added to the config.ru

Might be worth adding something like this as a resource in the readme: https://stackoverflow.com/questions/5166484/sending-a-delete-request-from-sinatra

@cernanb @ruthmesfun

**Comment by cjbrock** [comment]
Thanks for your feedback! 

// Corinna
