### ISSUE TITLE
Misleading information on The Prop being passed

### ISSUE THREAD

**Issue by jmulloy** [learn-co-curriculum/nyc-sinatra#59]
We were passing down the prop as suggested in the reading for the lab but we also needed to pass the pet object as well in order to get the functionality we needed. the state of the data was changing each time we would adopt a pet and then filter through the animals.

**Comment by sgharms** [comment]
@jmulloy 

I couldn't find mention of the word "prop"  or of a partial anywhere in this README. Could you please clarify which section is problematic? Pending your reply I'll close this issue until it's actionable.

Regards,

steven
