### ISSUE TITLE
Unlimited Beyonce

### ISSUE THREAD

**Issue by BenitolSantos** [learn-co-curriculum/nyc-sinatra#60]
The Landmarks View Controller Spec doesn't have a .destroy_all for figures, leading to crazy amounts of Beyonce. 

[1] pry(#<LandmarksController>)> Figure.all
=> [#<Figure:0x000000000449fe40 id: 1, name: "Beyonce">,
 #<Figure:0x000000000449fcb0 id: 2, name: "Beyonce">,
 #<Figure:0x000000000449fb70 id: 3, name: "Beyonce">,
 #<Figure:0x000000000449f918 id: 4, name: "Beyonce">,
 #<Figure:0x000000000449f788 id: 5, name: "Beyonce">,
 #<Figure:0x000000000449f508 id: 6, name: "Beyonce">,
 #<Figure:0x000000000449f378 id: 7, name: "Beyonce">,
 #<Figure:0x000000000449f1c0 id: 8, name: "Beyonce">,
 #<Figure:0x000000000449eea0 id: 9, name: "Beyonce">,
 #<Figure:0x000000000449ed38 id: 10, name: "Beyonce">,
 #<Figure:0x000000000449ebf8 id: 11, name: "Beyonce">,
 #<Figure:0x000000000449ea40 id: 12, name: "Beyonce">,
 #<Figure:0x000000000449e8b0 id: 13, name: "Beyonce">,
 #<Figure:0x000000000449e770 id: 14, name: "Beyonce">,
 #<Figure:0x000000000449e630 id: 15, name: "Beyonce">,
 #<Figure:0x000000000449e4a0 id: 16, name: "Beyonce">,
 #<Figure:0x000000000449e338 id: 17, name: "Beyonce">,
 #<Figure:0x000000000449e158 id: 18, name: "Beyonce">,
 #<Figure:0x000000000449dfc8 id: 19, name: "Beyonce">,
 #<Figure:0x000000000449de60 id: 20, name: "Beyonce">,
 #<Figure:0x000000000449dcd0 id: 21, name: "Beyonce">,
 #<Figure:0x000000000449db40 id: 22, name: "Beyonce">,
 #<Figure:0x000000000449d910 id: 23, name: "Beyonce">,
 #<Figure:0x000000000449d758 id: 24, name: "Beyonce">,
 #<Figure:0x000000000449d5f0 id: 25, name: "Beyonce">,
 #<Figure:0x000000000449d438 id: 26, name: "Beyonce">,
 #<Figure:0x000000000449d2a8 id: 27, name: "Beyonce">,
 #<Figure:0x000000000449d0a0 id: 28, name: "Beyonce">,
 #<Figure:0x000000000449cec0 id: 29, name: "Beyonce">,
 #<Figure:0x000000000449cd30 id: 30, name: "Beyonce">,
 #<Figure:0x000000000449cbc8 id: 31, name: "Beyonce">,
 #<Figure:0x000000000449ca10 id: 32, name: "Beyonce">,
 #<Figure:0x000000000449c858 id: 33, name: "Beyonce">,
 #<Figure:0x000000000449c650 id: 34, name: "Beyonce">,
 #<Figure:0x000000000449c4c0 id: 35, name: "Beyonce">,
 #<Figure:0x000000000449c358 id: 36, name: "Beyonce">,
 #<Figure:0x000000000449c1a0 id: 37, name: "Beyonce">,
 #<Figure:0x000000000449c010 id: 38, name: "Beyonce">,
 #<Figure:0x00000000044a3d88 id: 39, name: "Beyonce">,
 #<Figure:0x00000000044a3bf8 id: 40, name: "Beyonce">,
 #<Figure:0x00000000044a3a68 id: 41, name: "Beyonce">,
 #<Figure:0x00000000044a38d8 id: 42, name: "Beyonce">,
 #<Figure:0x00000000044a3748 id: 43, name: "Beyonce">,
 #<Figure:0x00000000044a3568 id: 44, name: "Beyonce">,
 #<Figure:0x00000000044a3388 id: 45, name: "Beyonce">,

**Comment by Sdcrouse** [comment]
Hi. Fellow student here. To fix this, just add this line of code to the `after` block in the `landmarks_controller_view_spec.rb` file: `Figure.destroy_all`

So, the block would ultimately look like this:
```
after do
    Landmark.destroy_all
    Figure.destroy_all
end
```
(And just to be clear, @BenitolSantos, this comment is directed at the Learn engineers, not you.)

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.
We have updated the materials and believe your issue to have been resolved.
