### ISSUE TITLE
The test needs to have a fully filled out Landmark

### ISSUE THREAD

**Issue by jmburges** [learn-co-curriculum/nyc-sinatra#8]
Landmark.figure shouldn't be `nil`. It should be filled out so that the show page doesn't fail

https://github.com/learn-co-curriculum/nyc-sinatra/blob/adcc3ab7438503ab4702443ae67138c8c75d07e8/spec/controllers/landmarks_controller_spec.rb#L5

**Comment by AnnJohn** [comment]
feel free to close if this has already been addressed
